### ISSUE TITLE
Skysat_stereo Problem

### ISSUE THREAD

**Issue by tatig80** [uw-cryo/skysat_stereo#19]
Hello,

I'm trying to run the skysat_stereo scripts.
The installation seems fine, but when I run ./skysat_triplet_pipeline.py I have this error:

xxxxx@ctsat: /src/skysat_stereo/scripts$ ./skysat_triplet_pipeline.py /media/dati/xxxxx/Skysat/TestUncalib/ /media/dati/xxxxx/Skysat/TestUncalib/RefDEM/
Traceback (most recent call last):
File "./skysat_triplet_pipeline.py", line 5, in
from rpcm import geo
File "/home/ganci/.local/lib/python3.8/site-packages/rpcm/init.py", line 8, in
import srtm4
File "/home/ganci/.local/lib/python3.8/site-packages/srtm4/init.py", line 7, in
from srtm4.raster import crop
File "/home/ganci/.local/lib/python3.8/site-packages/srtm4/raster.py", line 15, in
pyproj.network.set_network_enabled(active=True)
AttributeError: module 'pyproj' has no attribute 'network'
xxxxx@ctsat:~/src/skysat_stereo/scripts$

I don't know how to solve this problem.
Can you please help me with this issue?
Many thanks

**Comment by ShashankBice** [comment]
Hi @tatig80,
Thanks for reporting this. I have not come across this error myself, but I think this an error due to pyproj versioning. I am trying hard to update the package with the latest ASP and GDAL/PROJ, and hopefully this bug will be fixed with those updates.
I will let you know when the updates from devel branch are integrated into the main branch.
Thanks,
Shashank

**Comment by tatig80** [comment]
Thank you @ShashankBice
